Code challenge
glecie18/Javascript-Training pull request #16
Opened 2024-11-29 06:23 UTC by glecie18

For dev review

2024-12-11 07:10 UTC, chemagaton24 commented on select by tag name/index.html
> +    <script src="app.js"></script>
The `app.js` doesn't exist

I think the file should be
```suggestion
    <script src="apps.js"></script>
```

2024-12-11 07:11 UTC, chemagaton24 commented on Select ID type/script.js
> +const button = document.getElementById('btn-phrase');
Looks like this script is looking for an element with id of `btn-phrase` but there is no html file in this folder. Please provide

2024-12-11 07:12 UTC, chemagaton24 commented on Select ID type/script.js
> +const input = document.getElementById('input-phrase');
Looks like this script is looking for an element with id of `input-phrase` but there is no html file in this folder. Please provide

2025-01-16 07:35 UTC, arvin-viar requested changes
Please see comments

2025-01-16 07:35 UTC, arvin-viar commented on return elements using css selector/app.js
> +let footerImages = document.querySelectorAll('footer img');
use `const` since the variables was not assigned a new value

2025-01-16 07:35 UTC, arvin-viar commented on modifying elements/app.js
> +let inputValue = document.querySelector('input').value;
use `const` since the variable was not assigned a new value

2025-01-16 07:35 UTC, arvin-viar commented on select by tag name/apps.js
> +let listItems = document.getElementsByTagName('li');
we can use `const` here since we are changing the element of the array

2025-01-16 07:35 UTC, arvin-viar commented on return elements using css selector/index.html
> +    <link rel="stylesheet" href="css/normalize.css">
doesn't seem to be included in the files, we can remove this line

2025-01-16 07:35 UTC, arvin-viar commented on return elements using css selector/index.html
> +    <link rel="stylesheet" href="css/main.css">
doesn't seem to be included in the files, we can remove this line

2025-01-16 07:35 UTC, arvin-viar commented on return elements using css selector/index.html
> +    <link rel="stylesheet" href="css/responsive.css">
doesn't seem to be included in the files, we can remove this line

2025-01-16 07:35 UTC, arvin-viar commented on return elements using css selector/index.html
> +              <img src="img/numbers-01.jpg" alt="The number 1 painted with colors and textures.">
missing image file

2025-01-16 07:35 UTC, arvin-viar commented on return elements using css selector/index.html
> +              <img src="img/numbers-02.jpg" alt="The number 2 painted with various colors blended together.">
missing image file

2025-01-16 07:35 UTC, arvin-viar commented on return elements using css selector/index.html
> +        <a href="https://twitter.com/treehouse"><img src="img/twitter-wrap.png" alt="Twitter Logo" class="social-icon"></a>
missing image file

2025-01-16 07:35 UTC, arvin-viar commented on return elements using css selector/index.html
> +        <a href="https://www.facebook.com/TeamTreehouse"><img src="img/facebook-wrap.png" alt="Facebook Logo" class="social-icon"></a>
missing image file

2025-01-16 08:20 UTC, glecie18 commented on Select ID type/script.js
> +const input = document.getElementById('input-phrase');
added the html file

2025-01-16 08:20 UTC, glecie18 commented on Select ID type/script.js
> +const button = document.getElementById('btn-phrase');
added the html file

2025-01-16 08:34 UTC, glecie18 commented
will pr another after the update

2025-01-16 08:34 UTC, closed without merging