node code challenge
glecie18/Javascript-Training pull request #22
Opened 2024-12-10 04:20 UTC by glecie18

for dev review

2025-01-16 07:48 UTC, arvin-viar requested changes
Please address minor change request

2025-01-16 07:48 UTC, arvin-viar commented on handling routes view/index.js
> +var routes = require("./routes");
use `const` instead of `var`

2025-01-16 07:48 UTC, arvin-viar commented on simply merge/index.js
> +var mergedContent = utilities.merge(emailTemplate, mailValues);
use `const` instead of `var`

2025-01-16 07:48 UTC, arvin-viar commented on simply merge/utilities.js
> +  var mergedContent = utilities.merge(emailTemplate, mailValues);
use `const` instead of `var`

2025-01-16 08:46 UTC, glecie18 reviewed
changes applied var to const

2025-01-17 08:35 UTC, arvin-viar approved these changes
LGTM!

2025-01-21 03:56 UTC, merged