Lanscape of java script
glecie18/Javascript-Training pull request #25
Opened 2024-12-18 10:03 UTC by glecie18

for dev review added style css

2025-01-16 07:23 UTC, arvin-viar requested changes
Hi @glecie18, please address PR comments

2025-01-16 07:23 UTC, arvin-viar commented on Practice basic JQuery/index.html
> +  <link rel="stylesheet" type="text/css" href="styles.css">
missing `styles.css` file, if the file is not included we can just remove this line

2025-01-16 07:23 UTC, arvin-viar commented on Practice basic JQuery/index.html
> +  <script src="js/jquery-3.2.1.min.js"></script>
missing `js` folder with `jquery-3.2.1.min.js`

2025-01-16 07:23 UTC, arvin-viar commented on Practice basic JQuery/index.html
> +  <script src="js/app.js"></script>
`app.js` in not inside a `js` folder
```suggestion
  <script src="app.js"></script>
```

2025-01-16 07:23 UTC, arvin-viar commented on Practice basic JQuery/app.js
> +      var restaurantName = $('#restaurantName').val();
use `const` instead of `var`

2025-01-16 07:23 UTC, arvin-viar commented on Practice basic JQuery/app.js
> +      var restaurantReview = $('#restaurantReview').val();
use `const` instead of `var`

2025-01-16 07:44 UTC, glecie18 commented
will pr another

2025-01-16 07:44 UTC, closed without merging

2025-01-17 08:14 UTC, arvin-viar commented
Hi @glecie18, next time you don't need to create a new PR to address the comments/change requests. You can follow this steps:
1. checkout branch: `git checkout Lanscape-of-javaScript` if you are currently on your working branch
2. stage updated files: `git add .` once changes are applied, stage all changed files (you can also do this per file)
3. commit changes: `git commit -m "{message regarding the changes}"` commit the change files with a message about the changes
4. push commit: `git push` once completed, you'll be able to see your changes to the PR with the branch your working on